#!/bin/bash

set -e

# https://stackoverflow.com/questions/59895/get-the-source-directory-of-a-bash-script-from-within-the-script-itself
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  TARGET="$(readlink "$SOURCE")"
  if [[ $TARGET == /* ]]; then
    SOURCE="$TARGET"
  else
    DIR="$( dirname "$SOURCE" )"
    SOURCE="$DIR/$TARGET" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  fi
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

# sinpe ya no funciona
#server_url="http://tsa.sinpe.fi.cr/tsaHttp/"
#server_url="https://freetsa.org/tsr"
server_url="https://safestamper.com/tsa"
ca_files_path=$DIR
#ca_file=$ca_files_path/certs/sinpeCA.pem
#ca_file=$ca_files_path/certs/freetsaCA.pem
ca_file=$ca_files_path/certs/safestamperCA.cer
function sign(){
    sudo gpg --armor --detach-sig "$1";
    sha1sum "$1" > "${1}.sha1";
    #openssl ts -query -data "${1}" -cert | tee "${1}.tsq" | curl -s -S -H 'Content-Type: application/timestamp-query' --data-binary @- https://freetsa.org/tsr -o "${1}.tsr" 
    openssl ts -query -data "$1" -sha1 -cert | curl -o "${1}.tsr" -sSH 'Content-Type: application/timestamp-query' --data-binary @- "$server_url";
    openssl ts -verify -data "$1" -in "${1}.tsr" -CAfile "$ca_file";
                               
}

function verify(){
    echo ; echo "---------------------------------------";
    echo "GPG verification:"
    gpg --verify  "${1}.asc" "$1" 2>&1 | grep ' signature\|Firma ';
    echo ; echo "SHA1 verification:"
    if [ "$(sha1sum $1)" = "$(cat $1.sha1)" ] ; then 
        echo "SHA1 coincide"; 
    else 
        echo "SHA1 no coincide"; 
        exit 1; 
    fi 
    echo ; echo "Timestamp verification:"
    openssl ts -verify -data "$1" -in "${1}.tsr" -CAfile "$ca_file" 2>&1| grep "Verification: OK" ;
    openssl ts -reply -in $1.tsr -text 2>&1 | grep "Time stamp";
}

function unify(){
	file=$(basename $1)
    dir=$(dirname $1)
    filename="${file%.*}"
    if [ -d "$1" ] ||  [ "$#" -ne 1 ]; then
        tar -zcf $filename.tar.gz "$@";
        tar -zcfW $filename.tar.gz ;
        echo "$dir/$filename.tar.gz";
    else
        echo "$dir/$file";
    fi
}

case "$1" in
	-h| --help ) 
        echo "help!"; 
	    echo "Created by Pablo Rodriguez cyanpablo@protonmail.com 2015-2019";
        echo "$ sign_tsa document"
        ;;
	-s|--sign ) 
        sign $2
        ;;
	-v|--verify )
        verify $2
        ;;
    -t|--tar )
        unify $2
        ;;
   	* ) 
        file=$(unify "$@")
        echo "Signing file: $file"
        sign $file
        verify $file
esac

