#!/bin/bash

set -x
set -e

#server_url="http://tsa.sinpe.fi.cr/tsaHttp/"
server_url="https://freetsa.org/tsr"
ca_files_path=$(whereis sign_tsa | awk -F" " '{print $2}' | sed "s/sign_tsa//g")
#ca_file=$ca_files_path/sinpeCA.pem
ca_file=$ca_files_path/freetsaCA.pem

function sign(){
    sudo gpg --armor --detach-sig "$1";
    sha1sum "$1" > "${1}.sha1";
    openssl ts -query -data "$1" -sha1 -cert | curl -o "${1}.tsr" -sSH 'Content-Type: application/timestamp-query' --data-binary @- "$server_url";
                               
}

function verify(){
    gpg --verify  "${1}.asc" "$1";echo ;
    sha1sum "$1";
    cat "${1}.sha1" ; echo; echo;
    openssl ts -verify -data "$1" -in "${1}.tsr" -CAfile "$ca_file";
    openssl ts -reply -in $1.tsr -text ;
}

case "$1" in
	-h| --help ) 
        echo "help!"; 
        ;;
	-s|--sign ) 
        sign $2
        ;;
	-v|--verify )
        verify $2
        ;;
   	* ) 
        sign $1
        verify $1
esac

